version: '3.7'

services:
  frontend:
    container_name: react_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/david-portofolio'
      - '/david-portofolio/node_modules'
    ports:
      - 3000:3000
